import 'package:json_annotation/json_annotation.dart';
import '../../domain/entities/user.dart';

part 'user_model.g.dart';

/// Data Transfer Object (DTO) for the User entity with JSON serialization.
///
/// This model handles serialization/deserialization of user data from API
/// responses and local storage. It extends the domain [User] entity and adds
/// JSON parsing capabilities via json_serializable.
///
/// The fromJson and toJson methods are generated by json_serializable.
@JsonSerializable()
class UserModel extends User {
  const UserModel({
    required super.id,
    required super.email,
    required super.name,
    required super.role,
    required super.assignedFarmIds,
    required super.createdAt,
    super.photoUrl,
    super.lastLoginAt,
  });

  /// Creates a [UserModel] from JSON data with safe fallback parsing for backend roles.
  factory UserModel.fromJson(Map<String, dynamic> json) {
    final rawRole = json['role'];
    UserRole roleEnum = UserRole.fieldOperator;
    if (rawRole != null) {
      final str = rawRole.toString().toLowerCase();
      if (str.contains('admin') || str.contains('sysadmin')) {
        roleEnum = UserRole.admin;
      } else if (str.contains('owner') || str.contains('manager')) {
        roleEnum = UserRole.farmManager;
      } else if (str.contains('staff') || str.contains('operator')) {
        roleEnum = UserRole.fieldOperator;
      } else if (str.contains('sale')) {
        roleEnum = UserRole.sales;
      } else if (str.contains('viewer')) {
        roleEnum = UserRole.viewer;
      }
    }
    return UserModel(
      id: json['id']?.toString() ?? json['userId']?.toString() ?? 'user_001',
      email: json['email']?.toString() ?? json['username']?.toString() ?? 'user@crabsense.app',
      name: json['name']?.toString() ?? json['fullName']?.toString() ?? json['username']?.toString() ?? 'User',
      role: roleEnum,
      assignedFarmIds: (json['assignedFarmIds'] as List<dynamic>?)?.map((e) => e.toString()).toList() ??
          (json['farmId'] != null ? [json['farmId'].toString()] : const ['farm_001']),
      createdAt: json['createdAt'] != null ? DateTime.tryParse(json['createdAt'].toString()) ?? DateTime.now() : DateTime.now(),
      photoUrl: json['photoUrl'] as String?,
      lastLoginAt: json['lastLoginAt'] != null ? DateTime.tryParse(json['lastLoginAt'].toString()) : null,
    );
  }

  /// Creates a [UserModel] from a domain [User] entity.
  factory UserModel.fromEntity(User user) => UserModel(
    id: user.id,
    email: user.email,
    name: user.name,
    role: user.role,
    assignedFarmIds: user.assignedFarmIds,
    createdAt: user.createdAt,
    photoUrl: user.photoUrl,
    lastLoginAt: user.lastLoginAt,
  );

  /// Converts this [UserModel] to JSON format.
  Map<String, dynamic> toJson() => _$UserModelToJson(this);

  /// Converts this [UserModel] to a domain [User] entity.
  User toEntity() => User(
    id: id,
    email: email,
    name: name,
    role: role,
    assignedFarmIds: assignedFarmIds,
    createdAt: createdAt,
    photoUrl: photoUrl,
    lastLoginAt: lastLoginAt,
  );

  @override
  UserModel copyWith({
    String? id,
    String? email,
    String? name,
    UserRole? role,
    List<String>? assignedFarmIds,
    String? photoUrl,
    DateTime? createdAt,
    DateTime? lastLoginAt,
  }) => UserModel(
    id: id ?? this.id,
    email: email ?? this.email,
    name: name ?? this.name,
    role: role ?? this.role,
    assignedFarmIds: assignedFarmIds ?? this.assignedFarmIds,
    createdAt: createdAt ?? this.createdAt,
    photoUrl: photoUrl ?? this.photoUrl,
    lastLoginAt: lastLoginAt ?? this.lastLoginAt,
  );
}

/// API response model returned by login and token-refresh endpoints.
///
/// Contains the authenticated [UserModel] plus both JWT tokens.
/// Field names follow the snake_case convention used by the backend API.
@JsonSerializable(explicitToJson: true)
class AuthResponse {
  const AuthResponse({
    required this.user,
    required this.accessToken,
    required this.refreshToken,
    required this.accessTokenExpiresAt,
    required this.refreshTokenExpiresAt,
  });

  factory AuthResponse.fromJson(Map<String, dynamic> json) {
    final payload = (json['data'] is Map<String, dynamic>)
        ? json['data'] as Map<String, dynamic>
        : json;

    final token = payload['accessToken'] ?? payload['access_token'] ?? payload['token'] ?? '';
    final refresh = payload['refreshToken'] ?? payload['refresh_token'] ?? '';

    final expiresAtRaw = payload['expiresAt'] ?? payload['accessTokenExpiresAt'] ?? payload['access_token_expires_at'];
    final expiresAt = expiresAtRaw != null
        ? (DateTime.tryParse(expiresAtRaw.toString()) ?? DateTime.now().add(const Duration(hours: 1)))
        : DateTime.now().add(const Duration(hours: 1));

    final refreshExpiresAtRaw = payload['refreshTokenExpiresAt'] ?? payload['refresh_token_expires_at'];
    final refreshExpiresAt = refreshExpiresAtRaw != null
        ? (DateTime.tryParse(refreshExpiresAtRaw.toString()) ?? DateTime.now().add(const Duration(days: 7)))
        : DateTime.now().add(const Duration(days: 7));

    final userJson = (payload['user'] is Map<String, dynamic>)
        ? payload['user'] as Map<String, dynamic>
        : payload;

    final user = UserModel.fromJson(userJson);

    return AuthResponse(
      user: user,
      accessToken: token.toString(),
      refreshToken: refresh.toString(),
      accessTokenExpiresAt: expiresAt,
      refreshTokenExpiresAt: refreshExpiresAt,
    );
  }

  Map<String, dynamic> toJson() => _$AuthResponseToJson(this);

  final UserModel user;

  @JsonKey(name: 'access_token')
  final String accessToken;

  @JsonKey(name: 'refresh_token')
  final String refreshToken;

  /// ISO-8601 string mapped to [DateTime]; falls back to 60 min from now
  /// when absent to avoid null-check cascades in callers.
  @JsonKey(name: 'access_token_expires_at', fromJson: _parseDateTimeOrDefault)
  final DateTime accessTokenExpiresAt;

  @JsonKey(name: 'refresh_token_expires_at', fromJson: _parseDateTimeOrDefault)
  final DateTime refreshTokenExpiresAt;

  /// Helper – converts an ISO-8601 string to [DateTime].
  /// Returns a safe default (60 min / 7 days) when the field is absent.
  static DateTime _parseDateTimeOrDefault(value) {
    if (value is String) return DateTime.parse(value);
    return DateTime.now().add(const Duration(hours: 1));
  }
}
