sonar.projectKey=CrabSense_CrabSenseApp
sonar.organization=crabsense
sonar.projectName=CrabSenseApp
sonar.sources=lib
sonar.tests=test
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/generated/**
sonar.sourceEncoding=UTF-8
