import 'alert_enums.dart';

/// Alert entity representing a system notification in the CrabSense system.
///
/// An Alert is generated by the system or IoT sensors to notify users of
/// conditions that require attention, such as water quality issues, equipment
/// failures, or crab health concerns.
///
/// This is a pure domain entity with no external dependencies.
/// All fields are immutable (final); use [copyWith] to create modified copies.
///
/// Requirements: 9.1-9.10
class Alert {
  const Alert({
    required this.id,
    required this.type,
    required this.severity,
    required this.title,
    required this.message,
    required this.recommendedActions,
    required this.createdAt,
    required this.status,
    this.sourceId,
    this.sourceType,
    this.acknowledgedAt,
    this.acknowledgedBy,
  });

  /// Unique identifier for the alert
  final String id;

  /// Category of the alert indicating its source or subject area
  final AlertType type;

  /// Severity level indicating the urgency of the alert
  final AlertSeverity severity;

  /// Short human-readable title for the alert
  final String title;

  /// Detailed description of what triggered the alert
  final String message;

  /// Optional identifier of the entity that triggered this alert
  /// (e.g., a box ID, sensor ID). Null for system-level alerts.
  final String? sourceId;

  /// Optional type label for the source entity
  /// (e.g., "box", "sensor", "system"). Null for system-level alerts.
  final String? sourceType;

  /// List of recommended actions the user can take to resolve the alert.
  /// May be empty for informational alerts.
  final List<String> recommendedActions;

  /// Timestamp when the alert was created
  final DateTime createdAt;

  /// Timestamp when the alert was acknowledged (null if not yet acknowledged)
  final DateTime? acknowledgedAt;

  /// Identifier of the user who acknowledged the alert
  /// (null if not yet acknowledged)
  final String? acknowledgedBy;

  /// Current processing status of the alert
  final AlertStatus status;

  /// Returns true if the alert has not been read by the user.
  ///
  /// Requirement 9.2.
  bool get isUnread => status.isUnread;

  /// Returns true if the alert is still active (not dismissed).
  ///
  /// Requirement 9.6.
  bool get isActive => status.isActive;

  /// Returns true if this is a critical alert requiring immediate action.
  ///
  /// Requirement 9.3.
  bool get isCritical => severity == AlertSeverity.critical;

  /// Returns the age of the alert since it was created.
  Duration get age => DateTime.now().difference(createdAt);

  /// Returns true if the alert is within the 30-day history window.
  ///
  /// Requirement 9.9.
  bool get isWithinHistoryWindow {
    final cutoff = DateTime.now().subtract(const Duration(days: 30));
    return createdAt.isAfter(cutoff);
  }

  /// Creates a copy of this alert with the given fields replaced.
  Alert copyWith({
    String? id,
    AlertType? type,
    AlertSeverity? severity,
    String? title,
    String? message,
    String? sourceId,
    String? sourceType,
    List<String>? recommendedActions,
    DateTime? createdAt,
    DateTime? acknowledgedAt,
    String? acknowledgedBy,
    AlertStatus? status,
  }) => Alert(
    id: id ?? this.id,
    type: type ?? this.type,
    severity: severity ?? this.severity,
    title: title ?? this.title,
    message: message ?? this.message,
    sourceId: sourceId ?? this.sourceId,
    sourceType: sourceType ?? this.sourceType,
    recommendedActions: recommendedActions ?? this.recommendedActions,
    createdAt: createdAt ?? this.createdAt,
    acknowledgedAt: acknowledgedAt ?? this.acknowledgedAt,
    acknowledgedBy: acknowledgedBy ?? this.acknowledgedBy,
    status: status ?? this.status,
  );

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is Alert &&
        other.id == id &&
        other.type == type &&
        other.severity == severity &&
        other.title == title &&
        other.message == message &&
        other.sourceId == sourceId &&
        other.sourceType == sourceType &&
        other.createdAt == createdAt &&
        other.acknowledgedAt == acknowledgedAt &&
        other.acknowledgedBy == acknowledgedBy &&
        other.status == status;
  }

  @override
  int get hashCode => Object.hash(
    id,
    type,
    severity,
    title,
    message,
    sourceId,
    sourceType,
    createdAt,
    acknowledgedAt,
    acknowledgedBy,
    status,
  );

  @override
  String toString() =>
      'Alert(id: $id, type: ${type.displayName}, '
      'severity: ${severity.displayName}, title: $title, '
      'sourceId: $sourceId, sourceType: $sourceType, '
      'status: ${status.displayName}, createdAt: $createdAt, '
      'acknowledgedAt: $acknowledgedAt, acknowledgedBy: $acknowledgedBy)';
}
